version: "3.9"

services:
  backend:
    build: ./server
    container_name: lms-backed
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - lms-net

  frontend:
    build: ./client
    container_name: lms-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - backend
    networks:
      - lms-net

  mongo:
    image: mongo:latest
    container_name: lms-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - lms-net


networks:
  lms-net:
    driver: bridge

volumes:
  mongo_data: